// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SabioExam.DATA;

#nullable disable

namespace SabioExam.DATA.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250808102509_Transaction_ForeignKey_Correction")]
    partial class Transaction_ForeignKey_Correction
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SabioExam.DATA.Entities.DiscountCode", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Code");

                    b.ToTable("DiscountCodes");
                });

            modelBuilder.Entity("SabioExam.DATA.Entities.Transaction", b =>
                {
                    b.Property<long>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TransactionId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiscountCodeCode")
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("TransactionId");

                    b.HasIndex("DiscountCodeCode");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("SabioExam.DATA.Entities.Transaction", b =>
                {
                    b.HasOne("SabioExam.DATA.Entities.DiscountCode", null)
                        .WithMany("Transactions")
                        .HasForeignKey("DiscountCodeCode");
                });

            modelBuilder.Entity("SabioExam.DATA.Entities.DiscountCode", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
